#ifndef _ME_FLASH_H
#define _ME_FLASH_H

#include "init.h"

// EEPROM 开始地址
#define FLASH_ADDRES 0x004010

int FLASH_DATA_TEM_SUM_READ();
bool FLASH_DATA_LED_STATUS_READ();
bool FLASH_DATA_TEM_STATUS_READ();
u8 FLASH_DATA_FAN_PWM_READ();
bool FLASH_DATA_HF_STATUS_READ();

void FLASH_DATA_HF_STATUS_WRITE(bool b);
void FLASH_DATA_TEM_SUM_WRITE(int d);
void FLASH_DATA_LED_STATUS_WRITE(bool b);
void FLASH_DATA_TEM_STATUS_WRTIE(bool b);
void FLASH_DATA_FAN_PWM_WRITE(u8 d);

#endif