#include "init.h"

void init()
{
  // 时钏初始化
  CLK_DeInit();
  CLK_HSECmd(DISABLE);
  CLK_HSICmd(ENABLE);
  CLK_LSICmd(ENABLE);
  CLK_CCOCmd(DISABLE);
  CLK_HSIPrescalerConfig(CLK_PRESCALER_HSIDIV1);

  // GPIO初始化
  GPIO_DeInit(GPIOA);
  GPIO_DeInit(GPIOB);
  GPIO_DeInit(GPIOC);
  GPIO_DeInit(GPIOD);

  GPIO_Init(LED_LED_PORT, LED_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW);             // LED_D
  GPIO_Init(TM1650_SCL_PORT, TM1650_SCL_PIN, GPIO_MODE_OUT_OD_HIZ_FAST);       // TM1650_SCL
  GPIO_Init(TM1650_SDA_PORT, TM1650_SDA_PIN, GPIO_MODE_OUT_OD_HIZ_FAST);       // TM1650_SDA
  GPIO_Init(SW_PORT, SW_PIN, GPIO_MODE_OUT_OD_LOW_SLOW);                       // SW
  GPIO_Init(FAN_PORT, FAN_PIN, GPIO_MODE_OUT_OD_LOW_SLOW);                     // FAN
  GPIO_Init(TEMP_PLAY_LED_PORT, TEMP_PLAY_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // TEMP_PLAY_D
  GPIO_Init(TEMP_STOP_LED_PORT, TEMP_STOP_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // TEMP_STOP_D
  // GPIO_Init(DS18B20_SDA_PORT, DS18B20_SDA_PIN, GPIO_MODE_OUT_OD_HIZ_FAST);     // DS18B20_DATA
  // GPIO_Init(LED_PORT, LED_PIN, GPIO_MODE_OUT_OD_LOW_FAST);                     // LED
  GPIO_Init(FAN_LED_PORT, FAN_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // FAN_D
  GPIO_Init(HF_PORT,HF_PIN,GPIO_MODE_OUT_OD_LOW_SLOW);             //HF_FAN
  GPIO_Init(MSD_PORT,MSD_PIN,GPIO_MODE_OUT_OD_HIZ_SLOW);          //MSD


  // TIM2 初始化
  TIM2_DeInit();
  TIM2_TimeBaseInit(TIM2_PRESCALER_128, 99);
  // PWM, 百分比与后面装载的值有关， 例： 1000， 50%的PWM 就是 TIM2_SetCompare3(500)
  TIM2_OC1Init(TIM2_OCMODE_PWM2,
               TIM1_OUTPUTSTATE_ENABLE,
               0,
               TIM2_OCPOLARITY_LOW);
  TIM2_OC3Init(TIM2_OCMODE_PWM2,
               TIM2_OUTPUTSTATE_ENABLE,
               0,
               TIM2_OCPOLARITY_LOW);
  TIM2_Cmd(DISABLE);

  // TIM1 初始化
  TIM1_DeInit();
  TIM1_TimeBaseInit(16, TIM1_COUNTERMODE_UP, 999, 0);
  TIM1_ARRPreloadConfig(ENABLE);
  TIM1_ITConfig(TIM1_IT_UPDATE, ENABLE);
  TIM1_Cmd(DISABLE);

  FLASH_DeInit();
}
