#include "init.h"

void init()
{
  // 时钏初始化
  CLK_ICKR_HSIEN;
  CLK->CKDIVR &= (u8)(~CLK_CKDIVR_HSIDIV);
  CLK->CKDIVR &= (u8)(~CLK_CKDIVR_CPUDIV);

  //DS18B20
  PC_DDR_DDR7=1;
  PC_CR1_C17=0;
  PC_CR2_C27=1;
  PC_ODR_ODR7=1;

  // LED_D
  PA_DDR_DDR1 = 1;
  PA_CR1_C11 = 0;
  PA_CR2_C21 = 0;
  PA_ODR_ODR1 = 0;

  // TM1650_SCL
  PB_DDR_DDR4 = 1;
  PB_CR1_C14 = 0;
  PB_CR2_C24 = 1;
  PB_ODR_ODR4 = 1;

  // TM1650_SDA
  PB_DDR_DDR5 = 1;
  PB_CR1_C15 = 0;
  PB_CR2_C25 = 1;
  PB_ODR_ODR5 = 1;

  // SW
  PC_DDR_DDR3 = 1;
  PC_CR1_C13 = 0;
  PC_CR2_C23 = 0;
  PC_ODR_ODR3 = 0;

  // FAN
  PA_DDR_DDR3 = 1;
  PA_CR1_C13 = 0;
  PA_CR2_C23 = 1;
  PA_ODR_ODR3 = 0;

  // LED
  PD_DDR_DDR4 = 1;
  PD_CR1_C14 = 0;
  PD_CR2_C24 = 1;
  PD_ODR_ODR4 = 0;

  // TEMP_PLAY_D
  PC_DDR_DDR5 = 1;
  PC_CR1_C15 = 0;
  PC_CR2_C25 = 0;
  PC_ODR_ODR5 = 0;

  // TEMP_STOP_D
  PC_DDR_DDR6 = 1;
  PC_CR1_C16 = 0;
  PC_CR2_C26 = 0;
  PC_ODR_ODR6 = 0;

  // FAN_D
  PD_DDR_DDR6 = 1;
  PD_CR1_C16 = 0;
  PD_CR2_C26 = 0;
  PD_ODR_ODR6 = 0;

  // HF_FAN
  PA_DDR_DDR2 = 1;
  PA_CR1_C12 = 0;
  PA_CR2_C22 = 0;
  PA_ODR_ODR2 = 0;

  // MSD
  PC_DDR_DDR4 = 1;
  PC_CR1_C14 = 0;
  PC_CR2_C24 = 0;
  PC_ODR_ODR4 = 1;

  // GPIO_Init(LED_LED_PORT, LED_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW);             // LED_D
  GPIO_Init(TM1650_SCL_PORT, TM1650_SCL_PIN, GPIO_MODE_OUT_OD_HIZ_FAST);       // TM1650_SCL
  GPIO_Init(TM1650_SDA_PORT, TM1650_SDA_PIN, GPIO_MODE_OUT_OD_HIZ_FAST);       // TM1650_SDA
  // GPIO_Init(SW_PORT, SW_PIN, GPIO_MODE_OUT_OD_LOW_SLOW);                       // SW
  // GPIO_Init(FAN_PORT, FAN_PIN, GPIO_MODE_OUT_OD_LOW_SLOW); // FAN
  // GPIO_Init(TEMP_PLAY_LED_PORT, TEMP_PLAY_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // TEMP_PLAY_D
  // GPIO_Init(TEMP_STOP_LED_PORT, TEMP_STOP_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // TEMP_STOP_D
  // GPIO_Init(DS18B20_SDA_PORT, DS18B20_SDA_PIN, GPIO_MODE_OUT_OD_HIZ_FAST);     // DS18B20_DATA
  // GPIO_Init(LED_PORT, LED_PIN, GPIO_MODE_OUT_OD_LOW_FAST); // LED
  // GPIO_Init(FAN_LED_PORT, FAN_LED_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // FAN_D
  // GPIO_Init(HF_PORT, HF_PIN, GPIO_MODE_OUT_OD_LOW_SLOW);           // HF_FAN
  // GPIO_Init(MSD_PORT, MSD_PIN, GPIO_MODE_OUT_OD_HIZ_SLOW); // MSD

  // TIM2 初始化
  TIM2_DeInit();
  TIM2_TimeBaseInit(TIM2_PRESCALER_128, 99);
  // PWM, 百分比与后面装载的值有关， 例： 1000， 50%的PWM 就是 TIM2_SetCompare3(500)
  TIM2_OC1Init(TIM2_OCMODE_PWM2,
               TIM1_OUTPUTSTATE_ENABLE,
               0,
               TIM2_OCPOLARITY_LOW);
  TIM2_OC3Init(TIM2_OCMODE_PWM2,
               TIM2_OUTPUTSTATE_ENABLE,
               0,
               TIM2_OCPOLARITY_LOW);
  TIM2_Cmd(DISABLE);

  // TIM1 初始化
  TIM1_DeInit();
  TIM1_TimeBaseInit(16, TIM1_COUNTERMODE_UP, 999, 0);
  TIM1_ARRPreloadConfig(ENABLE);
  TIM1_ITConfig(TIM1_IT_UPDATE, ENABLE);
  TIM1_Cmd(DISABLE);

  FLASH_DeInit();
}
